---
version: 2

registries:
  github-registry:
    type: docker-registry
    url: https://ghcr.io
    username: ${{github.actor}}
    password: ${{secrets.GH_TOKEN}}

  aws-ecr-public-registry:
    type: docker-registry
    url: https://public.ecr.aws
    username: ${{secrets.AWS_ACCESS_KEY_ID}}
    password: ${{secrets.AWS_SECRET_ACCESS_KEY}}

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: "scope"
    registries: ["github-registry","aws-ecr-public-registry"]

  - package-ecosystem: docker
    directory: "/.devcontainer"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: "scope"
    registries: ["github-registry"]

  - package-ecosystem: docker
    directories:
      - "/ansible"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    registries: ["aws-ecr-public-registry"]

  - package-ecosystem: docker
    directories:
      - "/aws-cdk"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    registries: ["aws-ecr-public-registry"]

  - package-ecosystem: docker
    directories:
      - "/packer"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    registries: ["aws-ecr-public-registry"]

  - package-ecosystem: docker
    directories:
      - "/terragrunt"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    registries: ["aws-ecr-public-registry"]
