[tool.poetry]
name = "lint-ci"
version = "1.1.0"
description = ""
authors = []
license = ""

[tool.poetry.dependencies]
python = "^3.13"
yamllint = "1.35.1"
shellcheck-py = "0.10.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
