---
services:
  devcontainer-docker-images:
    container_name: devcontainer-docker-images
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/home/vscode/docker-images:cached
    user: vscode
    tty: true
