---
services:
  devcontainer-ci-images:
    container_name: devcontainer-ci-images
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ..:/home/vscode/ci-images:cached
    user: vscode
    tty: true
