[tool.poetry]
name = "ansible-ci"
version = "1.0.0"
description = ""
authors = []
license = ""

[tool.poetry.dependencies]
python = "^3.13"
ansible = "11.1.0"
boto3 = "1.35.81"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
