---
name: 'build aws-cdk'

on:
  push:
    branches:
      - main
    paths:
      - 'aws-cdk/**'
  workflow_dispatch:

env:
  IMAGE: aws-cdk
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}

permissions:
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: 'setup qemu'
        uses: docker/setup-qemu-action@v3

      - name: 'setup docker buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'login to dockerhub'
        uses: docker/login-action@v3
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{env.DOCKERHUB_PASSWORD}}

      - name: 'extract version from dockerfile'
        id: extract_version
        run: |
          TAG=$(sed -n 's/^ARG AWSCDK_VERSION=v\?\([0-9.]*\).*/\1/p' ./${{env.IMAGE}}/Dockerfile)
          echo "TAG=${TAG#v}" >> $GITHUB_ENV
          echo "TAG=${TAG#v}"

      - name: 'push'
        uses: docker/bake-action@v5
        with:
          targets: push
          workdir: ./${{env.IMAGE}}
